name: Test Python Application
description: Run pytest for the project.

inputs:
  python-bin:
    description: Python executable used to run pytest
    required: false
    default: "python"
  pytest-args:
    description: Extra pytest arguments
    required: false
    default: "--verbose"
  test-path:
    description: Path to the test directory or file
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Run pytest
      shell: bash
      run: ${{ inputs.python-bin }} -m pytest ${{ inputs.pytest-args }} ${{ inputs.test-path }}
