[tool.poetry]
name = "fastapi-v1"
version = "0.0.0"
description = "Add you application description here..."
authors = ["Daniel Andersson <d.andersson86@icloud.com>"]
readme = "README.md"
packages = [{ include = "*", from = "src" }]

[tool.poetry.dependencies]
bpython = "^0.24"
fastapi = "^0.120.1"
fastapi-cli = "^0.0.5"
nanoid = "^2.0.0"
python = "^3.11"
pydantic = "^2.9.2"
pydantic-settings = "^2.5.2"
python-dotenv = "^1.0.1"
requests = "^2.32.3"
uvicorn = "^0.30.6"
websockets = "^14.1"
python-multipart = "^0.0.27"
bcrypt = "4.0.1"
pyjwt = "^2.13.0"
python-jose = "^3.5.0"
starlette = "^0.49.1"
httptools = "^0.8.0"
typer = "^0.26.0"
jinxed = "^2.0.4"
snowballstemmer = "^3.1.0"
blessed = "^1.44.0"
sqlalchemy = "^2.0.50"

[tool.poetry.group.database_orm.dependencies]
sqlalchemy = "^2.0.35"
alembic = "^1.13.3"

[tool.poetry.group.mongidb.dependencies]
beanie = "^1.26.0"
motor = "^3.6.1"
pymongo = "^4.0.0"

[tool.poetry.group.postgres.dependencies]
asyncpg = "^0.29.0"
psycopg2-binary = "^2.9.9"
psycopg = { extras = ["binary", "pool"], version = "^3.2.2" }

[tool.poetry.group.sqlite.dependencies]
aiosqlite = "^0.20.0"

[tool.poetry.group.test.dependencies]
faker = "^28.4.1"
pytest = "^8.3.3"

[tool.poetry.group.dev.dependencies]
black = "^26.3.1"
flake8 = "^7.1.1"
isort = "^5.13.2"
mypy = "^1.11.2"
pylint = "^3.2.7"

[tool.poetry.group.docs.dependencies]
sphinx = "^8.2.3"
sphinx-rtd-theme = "^3.0.2"
sphinx-favicon = "^1.0.1"
sphinxcontrib-httpdomain = "^1.8.1"
sphinx-autodoc-typehints = "^3.2.0"
toml = "^0.10.2"
myst-parser = "^4.0.1"

[tool.poetry.extras]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.black]
line-length = 88
target-version = ["py311"]
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88
py_version = 311
src_paths = ["src", "tests"]
skip_gitignore = true
