[tool.poetry]
name = "fastapi-v1"
version = "0.0.0"
description = "Add you application description here..."
authors = ["Daniel Andersson <d.andersson86@icloud.com>"]
readme = "README.md"
packages = [{ include = "*", from = "src" }]

[tool.poetry.dependencies]
bpython = "^0.24"
fastapi = { extras = ["all"], version = "^0.115.0" }
fastapi-cli = "^0.0.5"
nanoid = "^2.0.0"
python = "^3.11"
pydantic = "^2.9.2"
pydantic-settings = "^2.5.2"
python-dotenv = "^1.0.1"
requests = "^2.32.3"
uvicorn = "^0.30.6"
websockets = "^14.1"
python-jose = { extras = ["cryprography"], version = "^3.5.0" }
python-multipart = "^0.0.20"
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
bcrypt = "4.0.1"

[tool.poetry.group.database_orm.dependencies]
sqlalchemy = "^2.0.35"
alembic = "^1.13.3"

[tool.poetry.group.mongidb.dependencies]
beanie = "^1.26.0"
motor = "^3.6.1"
pymongo = "^4.0.0"

[tool.poetry.group.postgres.dependencies]
asyncpg = "^0.29.0"
psycopg2-binary = "^2.9.9"
psycopg = { extras = ["binary", "pool"], version = "^3.2.2" }

[tool.poetry.group.sqlite.dependencies]
aiosqlite = "^0.20.0"

[tool.poetry.group.test.dependencies]
faker = "^28.4.1"
pytest = "^8.3.3"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
flake8 = "^7.1.1"
isort = "^5.13.2"
mypy = "^1.11.2"
pylint = "^3.2.7"

[tool.poetry.group.docs.dependencies]
sphinx = "^8.2.3"
sphinx-rtd-theme = "^3.0.2"
sphinx-favicon = "^1.0.1"
sphinxcontrib-httpdomain = "^1.8.1"
sphinx-autodoc-typehints = "^3.2.0"
toml = "^0.10.2"
myst-parser = "^4.0.1"

[tool.poetry.extras]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
