#!/usr/bin/env python3
# -*- coding: utf-8 -*-


"""
This module provides middleware for logging HTTP requests and responses in
a FastAPI application.

It defines the LoggerMiddleware class, which logs incoming request details
and outgoing response details using a configured logger. The logger is
initialized based on application settings, allowing for customizable
logging behavior. This middleware is intended to be added to the FastAPI
middleware stack to enable consistent and centralized logging of API
interactions for monitoring and debugging purposes.
"""

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.responses import Response

from src.core.env_config import get_settings
from src.core.logger_config import init_logger


class LoggerMiddleware(BaseHTTPMiddleware):
    """
    Middleware for logging HTTP request and response details in a FastAPI
    application.

    This middleware captures and logs information about each incoming HTTP
    request and its corresponding response using a configured logger. It is
    intended to be added to the FastAPI middleware stack to provide
    centralized logging for monitoring and debugging purposes.
    """

    def __init__(self, app):
        """
        Initialize the LoggerMiddleware with the given FastAPI application.

        Retrieves application settings and initializes the logger based on the
        configured logger name. Sets up the middleware to intercept and log
        HTTP requests and responses.

        :param app: The FastAPI application instance to which this
            middleware is attached.
        :type app: FastAPI
        """
        settings = get_settings()
        super().__init__(app)
        self.logger = init_logger(settings.app_logger_name)

    async def dispatch(self, request: Request, call_next) -> Response:
        """
        Intercepts each HTTP request to log request and response details.

        This method logs information about the incoming request before
        passing it to the next middleware or route handler. After receiving
        the response, it logs response details and returns the response to
        the client.

        :param request: The incoming HTTP request object.
        :type request: starlette.requests.Request
        :param call_next: Callable that forwards the request to the next
            middleware or route handler.
        :type call_next: Callable
        :return: The HTTP response object generated by the downstream handler.
        :rtype: starlette.responses.Response
        """
        self.log_request_details(request)
        response = await call_next(request)
        self.log_response_details(response)

        return response

    def log_request_details(self, request: Request):
        """
        Log detailed information about the request

        :param request: Request object
        :type request: Request
        """
        self.logger.info("Request details: %s %s", request.method, request.url)

    def log_response_details(self, response: Response):
        """
        Log detailed information about the response

        :param response: Response object
        :type response: Response
        """
        self.logger.info("Response details: %s", response.status_code)
