name: Lint Python Source
description: Run pylint checks against a target path.

inputs:
  python-bin:
    description: Python executable used to run pylint
    required: false
    default: "python"
  target-path:
    description: Directory or file path to lint
    required: false
    default: "src"
  pylint-args:
    description: Extra pylint arguments
    required: false
    default: "--verbose"

runs:
  using: composite
  steps:
    - name: Run pylint
      shell: bash
      run: ${{ inputs.python-bin }} -m pylint ${{ inputs.pylint-args }} ${{ inputs.target-path }}
