# This is a workflow to build documentation with Sphinx and then publish
#  the documentation to GitHub pages. The idea is to avoid any documentation
# later or by a third party. Simply write docstrings to document your code
# while coding.
name: Build and deploy documentation to GH-pages

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or
# in parallel
jobs:
  # This workflow contains a single job called "build"
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
        fetch-depth: 0

    - name: Setup Python v3.11.7
      uses: actions/setup-python@v5
      with:
        python-version: "3.11.7"

    - uses: abatilo/actions-poetry@v3
    - name: Install dependencies
      run: poetry install --with docs

    - name: Build docs with Sphinx
      run: |
        mkdir gh-pages
        make sphinx-build-html-for-gh-pages

    - name: Deploy to GitHub Pages
      if: ${{ github.event_name == 'push' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./gh-pages
        publish_branch: gh-pages
