# This workflow will run test the application codebase
name: Install and test application

on:
    push:
        branches: [ main, master, stage, test ]
    pull_request:
        branches: [ main, master, stage, test ]

    workflow_dispatch:

jobs:
    lint_application:
        name: Lint application codebase
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Python + Poetry
              uses: ./.github/actions/setup-python-poetry
              with:
                python-version: "3.11"
                poetry-version: "1.8.3"
                cache-dependency-path: "**/poetry.lock"

            - name: Install dependencies
              uses: ./.github/actions/install-poetry-deps

            - name: Run linting
              uses: ./.github/actions/lint-python

    test_application:
        name: Run pytest suite
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Setup Python + Poetry
              uses: ./.github/actions/setup-python-poetry
              with:
                python-version: "3.11"
                poetry-version: "1.8.3"
                cache-dependency-path: "**/poetry.lock"

            - name: Install dependencies
              uses: ./.github/actions/install-poetry-deps

            - name: Run tests
              uses: ./.github/actions/test-python
