# This workflow will run test the application codebase
name: Install and test application

on:
    push:
        branches: [ main, master, stage, test ]
    pull_request:
        branches: [ main, master, stage, test ]

    workflow_dispatch:

jobs:
    run_tests:
        strategy:
            fail-fast: false
            matrix:
                python-version: [ "3.11.4" ]
                poetry-version: [ "1.8.3" ]
                os: [ ubuntu-latest, macos-latest, windows-latest ]
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Setup Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}

            - name: Run image
              uses: abatilo/actions-poetry@v2
              with:
                poetry-version: ${{ matrix.poetry-version }}

            - name: Install python dependencies with poetry
              run: poetry install

            - name: Lint application codebase with pylint
              run: poetry run pylint --verbose src

            - name: Test application with pytest
              run: poetry run pytest --verbose
